apiVersion: v1
kind: ConfigMap
metadata:
  name: pact-broker
  labels:
     name: pact-broker
data:
  PACT_BROKER_DATABASE_ADAPTER: "sqlite"
  PACT_BROKER_DATABASE_HOST: ""
  PACT_BROKER_DATABASE_NAME: "pact-broker.sqlite"
  # TODO: Move to secrets when using a real db
  PACT_BROKER_DATABASE_HOST_USERNAME: ""
  PACT_BROKER_DATABASE_HOST_PASSWORD: ""
  PACT_BROKER_PUBLIC_HEARTBEAT: "true"
  PACT_BROKER_WEBHOOK_HOST_WHITELIST: ""
  PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: "https"
